name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

      steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: 
        uses: index.html
        with:
          
      - name: no
        run: index.html

      - name: Build the project
        run: index.html

      - name: Lint
        run: index.html